### ISSUE TITLE
The value for Magna (Omega) Stamina in the enmity graph is different from the value in the sheet.

### ISSUE THREAD

**Issue by JayofOh** [hsimyu/motocal#46]
It seems that in the enmity graph, Magna/Omega Stamina gains less damage than in the sheet.
Example:

1)magna buff from summon set to 0, both values are the same
http://puu.sh/zFJdK/6f6a3cd2ca.png http://puu.sh/zFJfb/59449e2088.png

2)magna buff from summon set to 50, values are different
http://puu.sh/zFJit/62dd6b5a4f.png http://puu.sh/zFJjY/1497901f16.png

the difference grows bigger as the magna buff increases.
Sorry if english is hard to understand.

**Comment by hsimyu** [comment]
Thanks for the bug report.
I confirmed this is a mistake on the enmity(stamina) graph calculation.
I'll fix it asap

**Comment by hsimyu** [comment]
@JayofOh This was caused by my typo on the graph logic. 5b43d4fe7ec42d43c043dbac637340bf4e381c91 fixes it. Thanks!
